# Generated by Django 6.1.1 on 2026-09-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'تصویر جاذبه',
                'verbose_name_plural': 'تصاویر جاذبه\u200cها',
                'db_table': 'attraction_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'جاذبه',
                'verbose_name_plural': 'جاذبه\u200cها',
                'db_table': 'attractions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttractionTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'برچسب جاذبه',
                'verbose_name_plural': 'برچسب\u200cهای جاذبه',
                'db_table': 'attraction_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'تعامل',
                'verbose_name_plural': 'تعاملات',
                'db_table': 'interactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=36, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('profile_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, default=1.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'برچسب کاربر',
                'verbose_name_plural': 'برچسب\u200cهای کاربر',
                'db_table': 'user_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttractionProfiles',
            fields=[
                ('attraction', models.OneToOneField(db_column='attraction_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='core.attractions')),
                ('attraction_type', models.CharField(max_length=50)),
                ('visit_motivation', models.CharField(max_length=50)),
                ('environment', models.CharField(choices=[('urban', 'شهری'), ('rural', 'روستایی'), ('mountainous', 'کوهستانی'), ('forest', 'جنگلی'), ('desert', 'کویری'), ('coastal', 'ساحلی'), ('island', 'جزیره\u200cای'), ('wetland', 'تالابی'), ('river', 'رودخانه\u200cای'), ('lake', 'دریاچه\u200cای')], max_length=50)),
                ('cost_band', models.CharField(max_length=50)),
                ('travel_companion', models.CharField(max_length=50)),
                ('required_mobility', models.CharField(max_length=50)),
                ('best_visit_time', models.CharField(max_length=50)),
                ('best_season', models.CharField(max_length=50)),
                ('cltural_experience', models.CharField(max_length=50)),
                ('dominant_natural_element', models.CharField(max_length=50)),
                ('tourist_activity', models.CharField(max_length=50)),
                ('access_level', models.CharField(max_length=50)),
                ('visit_duration', models.CharField(max_length=50)),
                ('popularity_level', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'پروفایل جاذبه',
                'verbose_name_plural': 'پروفایل جاذبه\u200cها',
                'db_table': 'attraction_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='core.users')),
                ('nationality', models.CharField(default='iranian', max_length=20)),
                ('language', models.CharField(default='fa', max_length=10)),
                ('age_band', models.CharField(default='25_34', max_length=20)),
                ('budget_band', models.CharField(default='medium', max_length=20)),
                ('travel_style', models.CharField(default='balanced', max_length=20)),
                ('travel_party_type', models.CharField(default='solo', max_length=20)),
                ('activity_level', models.CharField(default='moderate', max_length=20)),
                ('mobility_level', models.CharField(default='no_limit', max_length=20)),
                ('season_preference', models.CharField(default='all_year', max_length=20)),
                ('religious_travel_preference', models.CharField(default='none', max_length=40)),
                ('ethnic_group', models.CharField(default='prefer_not_to_say', max_length=30)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
                'db_table': 'user_profiles',
                'managed': False,
            },
        ),
    ]
